server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/bookings/**
        - id: flight-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/flights/**

    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


      